### ISSUE TITLE
The binary version of its metadata is 1.9.0, expected version is 1.7.1.

### ISSUE THREAD

**Issue by akshaytandroid** [javaherisaber/FloatingOverlayView#1]
I love this project. Great job.

But when I implement this dependency, I get this error:

/Users/ABCD/.gradle/caches/transforms-3/e3fe978bae033c69c79e590bcb3b25a3/transformed/jetified-FloatingOverlayView-1.0.2-api.jar!/META-INF/FloatingOverlayView_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Comment by javaherisaber** [comment]
@akshaytandroid 
The library requires Kotlin 1.9.0 version in your `buildscript`

```bat
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
```
